// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930134655_Phase2_FinanceCore")]
    partial class Phase2_FinanceCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Finance.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normal_balance");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_accounts_parent_id");

                    b.ToTable("accounts", "finance");
                });

            modelBuilder.Entity("Domain.Finance.CostCenters.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cost_centers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_centers_code");

                    b.ToTable("cost_centers", "finance");
                });

            modelBuilder.Entity("Domain.Finance.FiscalPeriods.FiscalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_periods");

                    b.HasIndex("StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_periods_start_date");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_periods_year_month");

                    b.ToTable("fiscal_periods", "finance");
                });

            modelBuilder.Entity("Domain.Finance.JournalMappings.JournalMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_journal_mappings");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_journal_mappings_branch_id");

                    b.HasIndex("EventType", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_mappings_event_type_branch_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EventType", "BranchId"), false);

                    b.ToTable("journal_mappings", "finance");
                });

            modelBuilder.Entity("Domain.Finance.JournalMappings.JournalMappingLine", b =>
                {
                    b.Property<Guid>("JournalMappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_mapping_id");

                    b.Property<string>("Component")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("component");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<Guid>("CreditAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_account_id");

                    b.Property<Guid>("DebitAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("debit_account_id");

                    b.HasKey("JournalMappingId", "Component")
                        .HasName("pk_journal_mapping_lines");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_journal_mapping_lines_cost_center_id");

                    b.HasIndex("CreditAccountId")
                        .HasDatabaseName("ix_journal_mapping_lines_credit_account_id");

                    b.HasIndex("DebitAccountId")
                        .HasDatabaseName("ix_journal_mapping_lines_debit_account_id");

                    b.ToTable("journal_mapping_lines", "finance");
                });

            modelBuilder.Entity("Domain.Finance.JournalTemplates.JournalTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_journal_templates");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_templates_name");

                    b.ToTable("journal_templates", "finance");
                });

            modelBuilder.Entity("Domain.Finance.JournalTemplates.JournalTemplateLine", b =>
                {
                    b.Property<Guid>("JournalTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_template_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("side");

                    b.HasKey("JournalTemplateId", "LineNumber")
                        .HasName("pk_journal_template_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_template_lines_account_id");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_journal_template_lines_cost_center_id");

                    b.ToTable("journal_template_lines", "finance");
                });

            modelBuilder.Entity("Domain.Finance.Journals.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<Guid?>("ReversalOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_id");

                    b.Property<Guid?>("ReversedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_number")
                        .HasFilter("number IS NOT NULL");

                    b.HasIndex("ReversalOfId")
                        .HasDatabaseName("ix_journal_entries_reversal_of_id");

                    b.HasIndex("ReversedById")
                        .HasDatabaseName("ix_journal_entries_reversed_by_id");

                    b.HasIndex("BranchId", "Date")
                        .HasDatabaseName("ix_journal_entries_branch_id_date");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_source_type_source_id")
                        .HasFilter("source_id IS NOT NULL");

                    b.HasIndex("Status", "Date")
                        .HasDatabaseName("ix_journal_entries_status_date");

                    b.ToTable("journal_entries", "finance");
                });

            modelBuilder.Entity("Domain.Finance.Journals.JournalLine", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Credit", "Domain.Finance.Journals.JournalLine.Credit#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("credit");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Debit", "Domain.Finance.Journals.JournalLine.Debit#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("debit");
                        });

                    b.HasKey("JournalEntryId", "LineNumber")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_lines_account_id");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_journal_lines_cost_center_id");

                    b.ToTable("journal_lines", "finance");
                });

            modelBuilder.Entity("Domain.MasterData.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_code");

                    b.ToTable("branches", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Coops.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("house_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_coops");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_coops_branch_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coops_code");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("ix_coops_farmer_id");

                    b.ToTable("coops", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_term_days");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CreditLimit", "Domain.MasterData.Customers.Customer.CreditLimit#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("credit_limit");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TaxIdentity", "Domain.MasterData.Customers.Customer.TaxIdentity#TaxIdentity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsPkp")
                                .HasColumnType("boolean")
                                .HasColumnName("tax_identity_is_pkp");

                            b1.Property<string>("Nitku")
                                .HasMaxLength(22)
                                .HasColumnType("character varying(22)")
                                .HasColumnName("tax_identity_nitku");

                            b1.Property<string>("Npwp")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("tax_identity_npwp");
                        });

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_code");

                    b.ToTable("customers", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Farmers.Farmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Nik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("nik");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BankAccount", "Domain.MasterData.Farmers.Farmer.BankAccount#BankAccount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountHolderName")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("bank_account_account_holder_name");

                            b1.Property<string>("AccountNumber")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("bank_account_account_number");

                            b1.Property<string>("BankName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("bank_account_bank_name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TaxIdentity", "Domain.MasterData.Farmers.Farmer.TaxIdentity#TaxIdentity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsPkp")
                                .HasColumnType("boolean")
                                .HasColumnName("tax_identity_is_pkp");

                            b1.Property<string>("Nitku")
                                .HasMaxLength(22)
                                .HasColumnType("character varying(22)")
                                .HasColumnName("tax_identity_nitku");

                            b1.Property<string>("Npwp")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("tax_identity_npwp");
                        });

                    b.HasKey("Id")
                        .HasName("pk_farmers");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_farmers_branch_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_farmers_code");

                    b.ToTable("farmers", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_uom_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("BaseUomId")
                        .HasDatabaseName("ix_items_base_uom_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_items_code");

                    b.HasIndex("TaxCodeId")
                        .HasDatabaseName("ix_items_tax_code_id");

                    b.ToTable("items", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Items.ItemUomConversion", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uuid")
                        .HasColumnName("uom_id");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor");

                    b.HasKey("ItemId", "UomId")
                        .HasName("pk_item_uom_conversions");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_item_uom_conversions_uom_id");

                    b.ToTable("item_uom_conversions", "master");
                });

            modelBuilder.Entity("Domain.MasterData.TaxCodes.TaxCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("IncomeTaxArticle")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("income_tax_article");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("VatTreatment")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("vat_treatment");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tax_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tax_codes_code");

                    b.ToTable("tax_codes", "master");
                });

            modelBuilder.Entity("Domain.MasterData.TaxCodes.TaxRate", b =>
                {
                    b.Property<Guid>("TaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("rate_percent");

                    b.Property<decimal>("TaxBaseRatio")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("tax_base_ratio");

                    b.HasKey("TaxCodeId", "EffectiveFrom")
                        .HasName("pk_tax_rates");

                    b.ToTable("tax_rates", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Uoms.Uom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_uoms");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_uoms_code");

                    b.ToTable("uoms", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_term_days");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BankAccount", "Domain.MasterData.Vendors.Vendor.BankAccount#BankAccount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccountHolderName")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("bank_account_account_holder_name");

                            b1.Property<string>("AccountNumber")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("bank_account_account_number");

                            b1.Property<string>("BankName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("bank_account_bank_name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TaxIdentity", "Domain.MasterData.Vendors.Vendor.TaxIdentity#TaxIdentity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsPkp")
                                .HasColumnType("boolean")
                                .HasColumnName("tax_identity_is_pkp");

                            b1.Property<string>("Nitku")
                                .HasMaxLength(22)
                                .HasColumnType("character varying(22)")
                                .HasColumnName("tax_identity_nitku");

                            b1.Property<string>("Npwp")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("tax_identity_npwp");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_code");

                    b.ToTable("vendors", "master");
                });

            modelBuilder.Entity("Domain.MasterData.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CoopId")
                        .HasColumnType("uuid")
                        .HasColumnName("coop_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_warehouses_branch_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.HasIndex("CoopId")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_coop_id")
                        .HasFilter("coop_id IS NOT NULL");

                    b.ToTable("warehouses", "master");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractIncentive", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("basis");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("metric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("RangeFrom")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("range_from");

                    b.Property<decimal?>("RangeTo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("range_to");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Domain.Partnership.Contracts.ContractIncentive.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");
                        });

                    b.HasKey("ContractId", "LineNumber")
                        .HasName("pk_contract_incentives");

                    b.ToTable("contract_incentives", "partnership");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractInputPrice", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Domain.Partnership.Contracts.ContractInputPrice.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price");
                        });

                    b.HasKey("ContractId", "ItemId")
                        .HasName("pk_contract_input_prices");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_contract_input_prices_item_id");

                    b.ToTable("contract_input_prices", "partnership");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractLiveBirdPrice", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<decimal>("MinWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("min_weight_kg");

                    b.Property<decimal>("MaxWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("max_weight_kg");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PricePerKg", "Domain.Partnership.Contracts.ContractLiveBirdPrice.PricePerKg#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_per_kg");
                        });

                    b.HasKey("ContractId", "MinWeightKg")
                        .HasName("pk_contract_live_bird_prices");

                    b.ToTable("contract_live_bird_prices", "partnership");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.PartnershipContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("IncomeTaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("income_tax_code_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PlasmaProfitSharePercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("plasma_profit_share_percent");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("scheme");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_contracts_branch_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_code");

                    b.HasIndex("IncomeTaxCodeId")
                        .HasDatabaseName("ix_contracts_income_tax_code_id");

                    b.ToTable("contracts", "partnership");
                });

            modelBuilder.Entity("Domain.Partnership.Cycles.ProductionCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateOnly?>("ChickInDate")
                        .HasColumnType("date")
                        .HasColumnName("chick_in_date");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("contract_snapshot");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uuid")
                        .HasColumnName("coop_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid")
                        .HasColumnName("farmer_id");

                    b.Property<int?>("InitialPopulation")
                        .HasColumnType("integer")
                        .HasColumnName("initial_population");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("PlannedChickInDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_chick_in_date");

                    b.Property<int>("PlannedPopulation")
                        .HasColumnType("integer")
                        .HasColumnName("planned_population");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_production_cycles");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_production_cycles_branch_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_production_cycles_contract_id");

                    b.HasIndex("CoopId")
                        .IsUnique()
                        .HasDatabaseName("ix_production_cycles_coop_id_open")
                        .HasFilter("status IN ('Planned', 'Active', 'Harvesting')");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("ix_production_cycles_farmer_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_production_cycles_number");

                    b.ToTable("production_cycles", "partnership");
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("Domain.Roles.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.HasKey("RoleId", "Permission")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Domain.Users.UserBranch", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.HasKey("UserId", "BranchId")
                        .HasName("pk_user_branches");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_user_branches_branch_id");

                    b.ToTable("user_branches", "identity");
                });

            modelBuilder.Entity("Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Infrastructure.Numbering.DocumentSequence", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("Key")
                        .HasName("pk_document_sequences");

                    b.ToTable("document_sequences", "infrastructure");
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("outbox_messages", "infrastructure");
                });

            modelBuilder.Entity("Domain.Finance.Accounts.Account", b =>
                {
                    b.HasOne("Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_accounts_parent_id");
                });

            modelBuilder.Entity("Domain.Finance.JournalMappings.JournalMapping", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_mappings_branches_branch_id");
                });

            modelBuilder.Entity("Domain.Finance.JournalMappings.JournalMappingLine", b =>
                {
                    b.HasOne("Domain.Finance.CostCenters.CostCenter", null)
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_mapping_lines_cost_centers_cost_center_id");

                    b.HasOne("Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_mapping_lines_accounts_credit_account_id");

                    b.HasOne("Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DebitAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_mapping_lines_accounts_debit_account_id");

                    b.HasOne("Domain.Finance.JournalMappings.JournalMapping", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_mapping_lines_journal_mappings_journal_mapping_id");
                });

            modelBuilder.Entity("Domain.Finance.JournalTemplates.JournalTemplateLine", b =>
                {
                    b.HasOne("Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_template_lines_accounts_account_id");

                    b.HasOne("Domain.Finance.CostCenters.CostCenter", null)
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_template_lines_cost_centers_cost_center_id");

                    b.HasOne("Domain.Finance.JournalTemplates.JournalTemplate", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_template_lines_journal_templates_journal_template_id");
                });

            modelBuilder.Entity("Domain.Finance.Journals.JournalEntry", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_branches_branch_id");

                    b.HasOne("Domain.Finance.Journals.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reversal_of_id");

                    b.HasOne("Domain.Finance.Journals.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reversed_by_id");
                });

            modelBuilder.Entity("Domain.Finance.Journals.JournalLine", b =>
                {
                    b.HasOne("Domain.Finance.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_accounts_account_id");

                    b.HasOne("Domain.Finance.CostCenters.CostCenter", null)
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_lines_cost_centers_cost_center_id");

                    b.HasOne("Domain.Finance.Journals.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");
                });

            modelBuilder.Entity("Domain.MasterData.Coops.Coop", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coops_branches_branch_id");

                    b.HasOne("Domain.MasterData.Farmers.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coops_farmers_farmer_id");
                });

            modelBuilder.Entity("Domain.MasterData.Farmers.Farmer", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farmers_branches_branch_id");
                });

            modelBuilder.Entity("Domain.MasterData.Items.Item", b =>
                {
                    b.HasOne("Domain.MasterData.Uoms.Uom", null)
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_uoms_base_uom_id");

                    b.HasOne("Domain.MasterData.TaxCodes.TaxCode", null)
                        .WithMany()
                        .HasForeignKey("TaxCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_items_tax_codes_tax_code_id");
                });

            modelBuilder.Entity("Domain.MasterData.Items.ItemUomConversion", b =>
                {
                    b.HasOne("Domain.MasterData.Items.Item", null)
                        .WithMany("Conversions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_uom_conversions_items_item_id");

                    b.HasOne("Domain.MasterData.Uoms.Uom", null)
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_uom_conversions_uoms_uom_id");
                });

            modelBuilder.Entity("Domain.MasterData.TaxCodes.TaxRate", b =>
                {
                    b.HasOne("Domain.MasterData.TaxCodes.TaxCode", null)
                        .WithMany("Rates")
                        .HasForeignKey("TaxCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tax_rates_tax_codes_tax_code_id");
                });

            modelBuilder.Entity("Domain.MasterData.Warehouses.Warehouse", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouses_branches_branch_id");

                    b.HasOne("Domain.MasterData.Coops.Coop", null)
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_warehouses_coops_coop_id");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractIncentive", b =>
                {
                    b.HasOne("Domain.Partnership.Contracts.PartnershipContract", null)
                        .WithMany("Incentives")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_incentives_contracts_contract_id");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractInputPrice", b =>
                {
                    b.HasOne("Domain.Partnership.Contracts.PartnershipContract", null)
                        .WithMany("InputPrices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_input_prices_contracts_contract_id");

                    b.HasOne("Domain.MasterData.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_input_prices_items_item_id");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.ContractLiveBirdPrice", b =>
                {
                    b.HasOne("Domain.Partnership.Contracts.PartnershipContract", null)
                        .WithMany("LiveBirdPrices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_live_bird_prices_contracts_contract_id");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.PartnershipContract", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_branches_branch_id");

                    b.HasOne("Domain.MasterData.TaxCodes.TaxCode", null)
                        .WithMany()
                        .HasForeignKey("IncomeTaxCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_tax_codes_income_tax_code_id");
                });

            modelBuilder.Entity("Domain.Partnership.Cycles.ProductionCycle", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_cycles_branches_branch_id");

                    b.HasOne("Domain.Partnership.Contracts.PartnershipContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_production_cycles_contracts_contract_id");

                    b.HasOne("Domain.MasterData.Coops.Coop", null)
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_cycles_coops_coop_id");

                    b.HasOne("Domain.MasterData.Farmers.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_cycles_farmers_farmer_id");
                });

            modelBuilder.Entity("Domain.Roles.RolePermission", b =>
                {
                    b.HasOne("Domain.Roles.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Users.UserBranch", b =>
                {
                    b.HasOne("Domain.MasterData.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branches_branches_branch_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany("Branches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_branches_users_user_id");
                });

            modelBuilder.Entity("Domain.Users.UserRole", b =>
                {
                    b.HasOne("Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Domain.Finance.JournalMappings.JournalMapping", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Finance.JournalTemplates.JournalTemplate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Finance.Journals.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.MasterData.Items.Item", b =>
                {
                    b.Navigation("Conversions");
                });

            modelBuilder.Entity("Domain.MasterData.TaxCodes.TaxCode", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Domain.Partnership.Contracts.PartnershipContract", b =>
                {
                    b.Navigation("Incentives");

                    b.Navigation("InputPrices");

                    b.Navigation("LiveBirdPrices");
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
