namespace Web.Api.Endpoints;

public static class Tags
{
    public const string Users = "Users";
    public const string Roles = "Roles";
    public const string Branches = "Branches";
    public const string Uoms = "Units of Measure";
    public const string TaxCodes = "Tax Codes";
    public const string Items = "Items";
    public const string Warehouses = "Warehouses";
    public const string Vendors = "Vendors";
    public const string Customers = "Customers";
    public const string Farmers = "Farmers";
    public const string Coops = "Coops";
    public const string Contracts = "Partnership Contracts";
    public const string Cycles = "Production Cycles";
    public const string Accounts = "Finance - Chart of Accounts";
    public const string CostCenters = "Finance - Cost Centers";
    public const string FiscalPeriods = "Finance - Fiscal Periods";
    public const string JournalTemplates = "Finance - Journal Templates";
    public const string JournalMappings = "Finance - Auto Journal Mappings";
    public const string Journals = "Finance - Journals";
    public const string FinanceReports = "Finance - Reports";
    public const string PurchaseOrders = "Purchasing - Purchase Orders";
    public const string GoodsReceipts = "Inventory - Goods Receipts";
    public const string StockTransfers = "Inventory - Stock Transfers";
    public const string Stock = "Inventory - Stock";
    public const string StockReturns = "Inventory - Returns & Feed Mutations";
    public const string DailyRecordings = "Production - Daily Recordings";
    public const string SalesOrders = "Sales - Sales Orders";
    public const string DeliveryOrders = "Sales - Delivery Orders";
    public const string SalesInvoices = "Sales - Invoices";
    public const string CustomerReceipts = "Finance - Customer Receipts";
    public const string Receivables = "Finance - Receivables";
    public const string CreditNotes = "Sales - Credit Notes";
    public const string CashBankAccounts = "Finance - Cash & Bank Accounts";
    public const string CashTransactions = "Finance - Cash In/Out & Transfers";
    public const string BankReconciliations = "Finance - Bank Reconciliation";
    public const string VendorInvoices = "Finance - Vendor Invoices";
    public const string PaymentVouchers = "Finance - Payment Vouchers";
    public const string Payables = "Finance - Payables";
    public const string CycleCost = "Costing - Cycle Cost (HPP)";
    public const string PlasmaSettlements = "Costing - Plasma Settlements";
    public const string TaxReports = "Finance - Tax Reports";
    public const string Monitoring = "System - Monitoring";
    public const string Attachments = "Attachments";
    public const string Mobile = "Mobile";
    public const string WeightRanges = "Weight Ranges";
    public const string LiveBirdStock = "Production - Live Bird Stock";
}
